### PR TITLE
adds wells fargo

### PR DESCRIPTION
**Pull request by sinAshish**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @sinAshish, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 3bd1f7d).  See below for details:

```
wells-fargo.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @sinAshish, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit f3ae2d2). :heavy_check_mark:

**Comment by dougaitken** [comment]
Hey @sinAshish - I can't find anything about remote friendly, only Wells Fargo being a global company. This list is for companies who hire employees outside of an office location.

**Comment by sinAshish** [comment]
ok but wells fargo allows remote working.

**Comment by dougaitken** [comment]
I can [see an article that Wells Fargo has allowed employees to Work from Home](https://stories.wf.com/supporting-employees-covid-19-crisis) but this is COVID-19 related. I don't see anything about permanent remote working @sinAshish

**Comment by sinAshish** [comment]
ok. I'll add some other companies. I was keeping a track of some.

**Comment by auto-nylen** [comment]
Hi @sinAshish, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit fb2ffad).  See below for details:

```
kaggle.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hey @sinAshish can you add Kaggle to the readme and I'll get this merged, please?

**Comment by sinAshish** [comment]
I've added kaggle to readme

**Comment by sinAshish** [comment]
#917

**Comment by dougaitken** [comment]
Okay, I'll push them both in. Thanks.

**Pull request merged**
