### PR TITLE
Add new company - RailsCarma

### PR DESCRIPTION
**Pull request by rordevelopernik**
Added company provides jobs for remote developers

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [x] You are an employee of the company mentioned and confirm all included details are correct.
* [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [ ] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Review by KieranRobson — CHANGES_REQUESTED** [review]
Hi there, 

A company profile needs to be added alongside the README.md changes, please edit in the current PR or make a new PR with all the new changes. See the https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md for guidance.

**Comment by rordevelopernik** [comment]
Sorry  ***@***.*** *
I've updated  and added the company profile now as per your instructions.
Please just check and let me know.

Thanks

**Comment by rordevelopernik** [comment]
Done closed both the pull requests.

**Comment by rordevelopernik** [comment]
In One PR I'm not been able to do that. Let me try it once again.

**Comment by rordevelopernik** [comment]
Done.  Created a new one with both the readme and company profile changes
in one PR. Please just review it and add.

**Pull request closed without merging**
