### PR TITLE
Update Black Tangent company URLs

### PR DESCRIPTION
**Pull request by teohm**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @teohm Are you able to fill in the company profile with more information, please? 

Thanks,

**Comment by nylen** [comment]
It looks like everything is already filled in: https://remoteintech.company/black-tangent/

**Comment by teohm** [comment]
@dougaitken this PR only updates our website link :)

The full company profile was already filled-in previously:
https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/black-tangent.md

**Comment by dougaitken** [comment]
Aye. trust me to only look at the commit content. 

Thanks, @teohm !

**Pull request merged**
