### PR TITLE
Create kinsta.md

### PR DESCRIPTION
**Pull request by tomzur**
Hi there, I  created a description for our company Kinsta, we are a fully remote tech company. If you could list us that would be great, appreciated your help. Thank you

Signed-off-by: tomzur <tom@kinsta.com>

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [ ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [ ] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [ ] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by KieranRobson** [comment]
Hi @tomzur,

Could you edit the README.md file with your addition. This needs to be in alphabetical order

**Comment by tomzur** [comment]
@KieranRobson Hi Kieran, absolutely I just edited that file. Thank you

**Comment by KieranRobson** [comment]
@tomzur Rather than creating a new PR, you can make the changes in this patch and itll update this PR automatically 

Makes it easier for the build logs and also for reviewing, if you need a hand, let me know!

**Comment by palmiak** [comment]
@dougaitken @KieranRobson the second PR is closed, I added the `readme.md` here. Everything should be ok now :)

**Review by KieranRobson — APPROVED** [review]
Looks good to me!

**Review by dougaitken — APPROVED** [review]

**Pull request merged**
