### PR TITLE
added bitfinex

### PR DESCRIPTION
**Pull request by spencer1573**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @spencer1573, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 222386c).  See below for details:

```
README.md: Expected 3 table cells but found 2: [BITFINEX](/company-profiles/bitfinex.md)| Worldwide
README.md: Invalid content in Website column: <td><a href="/company-profiles/bitfinex.md">BITFINEX</a></td><td>Worldwide</td><td></td>

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @spencer1573, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit b524816).  See below for details:

```
README.md: Expected 3 table cells but found 2: [BITFINEX](/company-profiles/bitfinex.md) | Worldwide
README.md: Invalid content in Website column: <td><a href="/company-profiles/bitfinex.md">BITFINEX</a></td><td>Worldwide</td><td></td>

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @spencer1573, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 9fe71e3).  See below for details:

```
README.md: Expected 3 table cells but found 2: [Bitfinix](/company-profiles/bitfinex.md) | Worldwide
README.md: Invalid content in Website column: <td><a href="/company-profiles/bitfinex.md">Bitfinix</a></td><td>Worldwide</td><td></td>

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @spencer1573, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit c8850da). :heavy_check_mark:

**Comment by spencer1573** [comment]
So I'm gonna be honest. I'm doing hacktoberfest, this PR took a little research to figure out. To prevent spam this year all repositories that are not marked with the topic "hacktoberfest" are not eligible toward people trying to complete hacktoberfest. Just wondering if you guys could do me a solid and add "hacktoberfest" to your repo or add the "hacktoberfest-accepted" to this pull request.  You guys are the best!

**Comment by dougaitken** [comment]
Hey @spencer1573 can I ask you a solid? Let's drop this PR since this company profile doesn't give much.

Either add another company or look through the issues and add one from there?

**Comment by spencer1573** [comment]
sure! @spencer1573

**Pull request closed without merging**
