### PR TITLE
Issue 639

### PR DESCRIPTION
**Pull request by strawberries73**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @strawberries73, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 7cfa7f8).  See below for details:

```
black-pixel.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @strawberries73, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit c9a065a). :heavy_check_mark:

**Comment by dougaitken** [comment]
Hey @strawberries73 can I ask you to rename this to the new company and then delete the old company from the list and company profile file, please?

**Comment by strawberries73** [comment]
Yes. I will do that.

**Comment by strawberries73** [comment]
Hi @dougaitken, I added the new company and deleted the old one as requested.  The README is also updated.

**Comment by dougaitken** [comment]
Did you commit and push your changes @strawberries73? I don't see any new commits to this PR

**Comment by dougaitken** [comment]
I fixed it up @strawberries73 - thanks for your edit!

**Comment by strawberries73** [comment]
Thank you, I didn't realize that I pushed it to my forked repository.  I'm new and still learning the steps. I appreciate that you fixed it.

**Comment by dougaitken** [comment]
Not a problem @strawberries73 happy to help get people started!

**Pull request merged**
