### PR TITLE
Update compose.md

### PR DESCRIPTION
**Pull request by javariya**
Updating Compose company profile.

I have extracted company information from company website and LinkedIn profile. 

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @javariya, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 262840e).  See below for details:

```
compose.md: Invalid section: "Company Size".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
compose.md: Invalid section: "Remote Status".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
compose.md: Invalid section: "Company Technologies".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
compose.md: Invalid section: "Office Locations".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
compose.md: Invalid section: "LinkedIn".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
compose.md: Empty section: "How to apply". Fill it in or leave it out instead.
compose.md: Profile looks complete, but the main readme contains a warning emoji.

7 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @javariya, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 6cb5068).  See below for details:

```
compose.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by javariya** [comment]
Hello,

I have fixed the issues but I am not sure why the automated check is pointing towards an issue in Readme.md because I have not edited it in any way. Kindly let me know if something else needs to be fixed. 

Regards
Javariya

**Comment by dougaitken** [comment]
This is handled in #949

Please do open a new PR with another edit from further down the list.

Thanks,

**Pull request closed without merging**
