### PR TITLE
Validate company sort order in readme; try out comment bot

### PR DESCRIPTION
**Pull request by nylen**
This PR makes some changes to validate the sort order of companies in the readme.

As with https://github.com/remoteintech/remote-jobs/pull/378, it should fail at first because the existing data doesn't pass the new validation, then I'll make another commit to clean things up.

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of
commit 1a30022).  See below for details:

```
README.md: Company is listed out of order: "Cards Against Humanity" (should be before "Codestunts")
README.md: Company is listed out of order: "Convert" (should be before "CoreOS")
README.md: Company is listed out of order: "Crew" (should be before "Customer.io")
README.md: Company is listed out of order: "Datadog" (should be before "Datica")
README.md: Company is listed out of order: "Data Science Brigade" (should be before "Datadog")
README.md: Company is listed out of order: "HE:labs" (should be before "Help Scout")
README.md: Company is listed out of order: "Stairlin" (should be before "Stitch Fix")
README.md: Company is listed out of order: "Yonder" (should be before "YouCanBook.me Ltd")

8 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit 5eb4759).  See below for details:

```

```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit 5eb4759).  See below for details:

```
README.md: Company is listed out of order: "Cards Against Humanity" (should be before "Codestunts")
README.md: Company is listed out of order: "Convert" (should be before "CoreOS")
README.md: Company is listed out of order: "Crew" (should be before "Customer.io")
README.md: Company is listed out of order: "Datadog" (should be before "Datica")
README.md: Company is listed out of order: "Data Science Brigade" (should be before "Datadog")
README.md: Company is listed out of order: "HE:labs" (should be before "Help Scout")
README.md: Company is listed out of order: "Stairlin" (should be before "Stitch Fix")
README.md: Company is listed out of order: "Yonder" (should be before "YouCanBook.me Ltd")

8 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit eaf27f9).  See below for details:

```
README.md: Company is listed out of order: "HE:labs" (should be before "Help Scout")
README.md: Company is listed out of order: "Stairlin" (should be before "Stitch Fix")
README.md: Company is listed out of order: "Yonder" (should be before "YouCanBook.me Ltd")

3 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 4920494).

**Comment by dougaitken** [comment]
well aren't you fancy @nylen! 😍

**Pull request merged**
