### PR TITLE
Added iOS App Templates

### PR DESCRIPTION
**Pull request by mrcflorian**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @mrcflorian, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 5f010b2).  See below for details:

```
README.md: Company is listed out of order: "iOS App Templates" (should be before "IPS Group, Inc.")
README.md: Broken link to company "iOS App Templates": "/company-profiles/iosapptemplates.md"

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @mrcflorian, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 3e1476e).  See below for details:

```
README.md: Company is listed out of order: "iOS App Templates" (should be before "iwantmyname")
README.md: Broken link to company "iOS App Templates": "/company-profiles/iosapptemplates.md"

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
Hi @mrcflorian, the company profile in #554 looks good, but the readme edits and the company profile addition need to be done in the same PR.

**Comment by mrcflorian** [comment]
Let me merge the two

**Pull request closed without merging**
