### PR TITLE
adding new company Skuad

### PR DESCRIPTION
**Pull request by dogravishal**
This is a modified version of, and should adhere to, the [[Contributing Guidelines](url)]

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [x] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Review by KieranRobson — CHANGES_REQUESTED** [review]
Is this a site to hire other people as these are not present within this list, this is only for directly hiring employees.

**Comment by dogravishal** [comment]
> Is this a site to hire other people as these are not present within this list, this is only for directly hiring employees.

I have updated above list and directly employees have the opportunity to explore opportunities with [Skuad](https://www.skuad.io/) by visiting https://allremote.jobs/remote-companies/skuad-5.

**Comment by dogravishal** [comment]
> This is a modified version of, and should adhere to, the [[Contributing Guidelines](url)]
> 
> * [ ]  This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
> * [x]  You are an employee of the company mentioned and confirm all included details are correct.
> * [x]  You know your alphabet - company is listed in alphabetical order in the README.md file.
> * [x]  The company directly hires employees. ** No bootcamps / freelance sites / etc**
> * [x]  The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
> * [x]  A [company profile](/company-profiles/example.md) is included - This is **required** for new additions.
> * [x]  An entry has been added or edited within the [readme.md file](../../main/README.md).
> * [x]  **Remote status** has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
> * [x]  **Region** details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
> * [ ]  **How to apply** details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

**Comment by KieranRobson** [comment]
> Envision a world without borders where a company can find, hire, and manage talent regardless of location. A world where you can find work that speaks to your passion without having to move to another place. Skuad enables this!

I dont believe this fits this list as it is only for companies who directly hire employees rather than going through a middleman company.

**Pull request closed without merging**
