### PR TITLE
Added a great translation company - LILT

### PR DESCRIPTION
**Pull request by fcpimenta**
This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [ ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x ] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @fcpimenta thanks for the contribution.

To be clear, this is an entry for a company which hires remote employees directly? I ask as almost all of the company profile hints at this but the apply link mentions becoming a translator.

**Comment by fcpimenta** [comment]
Hi Doug,

Thank you for the message. I thought about adding LILT because I work as a translator remotely, but I'm not hired directly (I'm not an employee).

If this addition is not what is expected, I can discard it and add another company for which I also work remotely.

**Comment by dougaitken** [comment]
Yes please @fcpimenta - this List is for companies which hire remote employees directly.

**Comment by fcpimenta** [comment]
Hi Doug,

As agreed, I added a Brazilian company that directly hires people with the option to work remotely (my daughter works there remotely). [PR #1587](https://github.com/remoteintech/remote-jobs/pull/1587)

**Pull request closed without merging**
