### PR TITLE
Jenna's Changes to Vox Media

### PR DESCRIPTION
**Pull request by jennaschultz**
I updated the Vox Media profile.

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @jennaschultz, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit f9de521).  See below for details:

```
vox-media.md: Invalid section: "Remote Opportunities".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @jennaschultz, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 7d881a8). :heavy_check_mark:

**Comment by dougaitken** [comment]
Hey @jennaschultz - thanks for the edit. 

Can you remove the HTML formatting from the company profile, and also add the region for Vox to the main readme. Thanks!

**Comment by jennaschultz** [comment]
Alright, I think I made and pushed those changes correctly.

**Comment by dougaitken** [comment]
Ah, there is a merge conflict, can you resolve that please @jennaschultz?

**Pull request closed without merging**
