### PR TITLE
Hyper Giant acquired Black Giant

### PR DESCRIPTION
**Pull request by xhika**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @xhika, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 42ce8f2).  See below for details:

```
black-pixel.md: Required section "Company blurb" not found.
black-pixel.md: Content is not part of any section: <p>Black Pixel has been acquired by Hypergiant Space Age Solutions further fuelingHypergiant Industries&apos; commercial software division.Learn more at <a href="http://www.hypergiant.com">www.hypergiant.com</a></p>
black-pixel.md: Content is not part of any section: <p>Link to md below:<a href="https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/hyper-giant.md">Hyper-giant</a></p>
hyper-giant.md: No link to company profile from readme

4 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @xhika, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 80feb5c).  See below for details:

```
README.md: Company is listed out of order: "Hyper-giant" (should be before "Hyperion")
README.md: Missing company profile for "Hyper-giant", or broken link: "/company-profiles//hyper-giant.md"
black-pixel.md: Profile looks incomplete, but the "Company blurb" does not contain a warning emoji.
hyper-giant.md: No link to company profile from readme

4 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @xhika, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 987b65e).  See below for details:

```
README.md: Missing company profile for "Hyper-giant", or broken link: "/company-profiles//hyper-giant.md"
black-pixel.md: Profile looks incomplete, but the "Company blurb" does not contain a warning emoji.
hyper-giant.md: No link to company profile from readme

3 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @xhika, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit efd71ef).  See below for details:

```
black-pixel.md: Profile looks incomplete, but the "Company blurb" does not contain a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by xhika** [comment]
Should black pixel be left or removed since it been acquired by Hypergiant?

**Comment by auto-nylen** [comment]
Hi @xhika, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 9b64ed8).  See below for details:

```
black-pixel.md: Invalid section: "Company blurb &#x26A0;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
black-pixel.md: Required section "Company blurb" not found.

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hi @xhika this was resolved in #816 

I'm closing off this PR, please do open another.

**Pull request closed without merging**
