### PR TITLE
Update Codeship company information

### PR DESCRIPTION
**Pull request by missnadia**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @missnadia 

Can you make the region `Worldwide` only, please? Anything about offices and such is kept in the readme. 

Thanks!

**Comment by missnadia** [comment]
@dougaitken all set -- changed region to Worldwide. The region was already filled out so I didn't think i needed make any changes there.

**Comment by lostnco1** [comment]
@Missnadia @dougaitken @freeformz @ntalbott whats up guys thanks for all your help and amazing work what can I do to make sure i understand the correct information that I need to use

**Comment by dougaitken** [comment]
Just noticed - the URL in the company profile is for Rollout which lists Israel as the location. Is that correct @missnadia?

**Comment by missnadia** [comment]
@dougaitken yes. CloudBees is their parent company and lists the Tel Aviv location as one of their offices. Also in the job listing page, the non-remote location for one of the openings for a Site Reliability Engineer lists the location as Tel Aviv, Israel: https://codeship.com/jobs?gh_jid=1939368

**Comment by dougaitken** [comment]
Ah, thanks for @missnadia

Can you pull my changes and revert, please? Make sure to keep the correct URL though.

**Comment by missnadia** [comment]
@dougaitken i kept the blurb in the remote section and reverted the other changes.

**Pull request merged**
