### PR TITLE
add kodify.io

### PR DESCRIPTION
**Pull request by jpita**
This is a modified version of the [Contributing Guidelines](/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](/CODE_OF_CONDUCT.md)
- [ ] This PR contains housekeeping (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [ ] A company profile is included - Not essential but it really helps!
- [x] The company directly hires employees - This may sounds odd but while awesome, this list is not for coding bootcamps, "teaching" positions a network (Teacher positions employed directly, such as Treehouse, are allowed), or networking sites for listing a CV looking for gigs
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [ ] A company-profile has been included for each addition to the list
- [ ] I am an employee of the company mentioned and confirm all details are correct
- [ ] **Remote status** has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] **Region** details any restrictions to applicants based on geography
- [ ] **How to apply** details the best approach for new applications, link to open positions, and any other help available for job hunters
- [ ] Any missing parts from the profile, please use <Unknown> to allow for future completion

interviewed there and have a friend working there

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @jpita can you add a company profile please?

**Comment by jpita** [comment]
@dougaitken what do u mean by company profile?
This is the company's site https://kodify.io/

**Comment by dougaitken** [comment]
Hi @jpita, here is the [example](https://github.com/jessicard/remote-jobs/blob/master/company-profiles/example.md) - this keeps a consistent look across the repository 👍

**Comment by jpita** [comment]
# Kodify

## Company blurb

Company that works on adult entertainment, tube sites and subscription sites

## Company size

20-50 people

## Remote status

You can work pretty much from everywhere

## Region

Company is based in Barcelona, Spain but you can work from everywhere

## Company technologies

NodeJS and JS. Not sure about the db's

## Office Locations

Barcelona, Spain

## How to apply

Mail to careers@kodify.io or apply on [linkedin] (https://www.linkedin.com/jobs/search?f_C=2771097&locationType=Y&trk=careers_promo_module_see_jobs)

**Comment by dougaitken** [comment]
Hey @jpita - going through old PRs - are you able to edit your PR and let me know once conflicts are resolved and you've added the company-profile as a file? Thanks!

**Comment by auto-nylen** [comment]
Hi @jpita, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit dad72d2).  See below for details:

```
README.md: Broken link to company "Kodify": "/company-profiles/kodify.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
:point_up: Fixing the bot to ping the author of the last commit instead of the PR author...

**Comment by auto-nylen** [comment]
Hi @undefined, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit 8c8ca14).  See below for details:

```
0 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 8c8ca14). :heavy_check_mark:

**Pull request merged**
