### PR TITLE
Added a New Remote Company Uhuru 

### PR DESCRIPTION
**Pull request by ksharma20**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @ksharma20, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 8590a8b).  See below for details:

```
README.md: Expected 3 table cells but found 4: [Udacity](/company-profiles/udacity.md) | https://www.udacity.com/ | Worldwide |
README.md: Expected 3 table cells but found 4: [Uhuru Networks](/company-profiles/Uhuru-Networks.md) | https://uhurunetwork.com/ | Worldwide (Austin) |
Uhuru-Networks.md: Expected 1 first-level heading but found 0
Uhuru-Networks.md: The main title is wrapped inside of another element.
Uhuru-Networks.md: Company name looks wrong: ""
Uhuru-Networks.md: Required section "Company blurb" not found.
Uhuru-Networks.md: Content is not part of any section: <p>Uhuru </p>
Uhuru-Networks.md: Content is not part of any section: <p>Company Blurb </p>
Uhuru-Networks.md: Content is not part of any section: <p>Uhuru Network is a world-class agency that specializes in growing businesses through web development (Agile Market Domination) and digital &amp; inbound marketing (Business Advantage). In fact, we&#x2019;re more than that&#x2014;our results compete with any business of any size.</p>
Uhuru-Networks.md: Content is not part of any section: <p>We don&#x2019;t simply participate we strive to dominate every market we serve. We consistently deliver excellence, we are intimidating to our competition and are embraced by employees, customers, and vendors.</p>
Uhuru-Networks.md: Content is not part of any section: <p>Clients repeatedly say we make their life simpler and business better, and they only wish they worked with Uhuru sooner. They have close relationships with us; they trust us and see us as a true partner in the success of their business.</p>
Uhuru-Networks.md: Content is not part of any section: <p>Our Mission (What are we doing?)Leave people better than we found them by transforming the way people and businesses execute sales and marketing.</p>
Uhuru-Networks.md: Content is not part of any section: <p>Uhuru Core Values (What matters most to us?)Core Values are the rules and boundaries that define the company&#x2019;s culture and personality and provide a final &#x201C;Should/Shouldn&#x2019;t&#x201D; test for all the behaviors and decisions by everyone in the company. The soul of Uhuru.</p>
Uhuru-Networks.md: Content is not part of any section: <ul><li>Always Educate</li><li>Encourage Individual Initiatives</li><li>Hyper Communication &amp; Clear Expectations</li><li>Good Fit</li><li>Practice What We Preach</li><li>Leave People Better than We Found Them</li><li>Give Them More Than What They Expect</li><li>We before me</li></ul>
Uhuru-Networks.md: Content is not part of any section: <p>BENEFITS :</p>
Uhuru-Networks.md: Content is not part of any section: <ul><li>Work Remotely! Yep, 100%! Anywhere in the world (with reliable internet)</li><li>Opportunity to attend top creative, online, &amp; marketing conferences</li><li>Yearly team travel experiences &amp; retreats</li><li>Maternity &amp; paternity leave</li><li>End of year bonus (based on performance)</li><li>Ongoing training and career development</li><li>6-month performance reviews &amp; salary increases</li></ul>
Uhuru-Networks.md: Content is not part of any section: <p>TO APPLY :<a href="https://uhurunetwork.com/careers/">https://uhurunetwork.com/careers/</a> </p>

17 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hi @ksharma20 

Can you edit the company readme to match the formatting of the example using Markdown, please?

**Comment by ksharma20** [comment]
Ohky Thanks alot for reviewing into it bro @dougaitken 
But tell me that Else I neeed to do now ?
Im seriously Too new to these stuff So I dont know that to do next !?
Help me out here too bro 
I will be very thankful to you 💯

**Comment by dougaitken** [comment]
Ideally what needs to happen @ksharma20 is the company profile matches the same format as the example, with the same sections. 

Can you look into doing that, please?

**Comment by dougaitken** [comment]
Closed via #1082

**Pull request closed without merging**
