### PR TITLE
Update previousnext.md

### PR DESCRIPTION
**Pull request by Joy-Hannn**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @Joy-Hannn, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 20e6d97).  See below for details:

```
previousnext.md: Invalid section: "&#x516C;&#x53F8;&#x7B80;&#x4ECB;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x516C;&#x53F8;&#x89C4;&#x6A21;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x8FDC;&#x7AEF;&#x72B6;&#x6001;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x5730;&#x533A;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x516C;&#x53F8;&#x6280;&#x672F;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x529E;&#x516C;&#x5730;&#x70B9;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x5982;&#x4F55;&#x7533;&#x8BF7;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Required section "Company blurb" not found.

8 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @Joy-Hannn, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit c4e22b6).  See below for details:

```
previousnext.md: Invalid section: "&#x516C;&#x53F8;&#x89C4;&#x6A21;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x8FDC;&#x7AEF;&#x72B6;&#x6001;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x5730;&#x533A;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x516C;&#x53F8;&#x6280;&#x672F;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x529E;&#x516C;&#x5730;&#x70B9;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Invalid section: "&#x5982;&#x4F55;&#x7533;&#x8BF7;".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
previousnext.md: Required section "Company blurb" not found.
previousnext.md: Content is not part of any section: <p>&#x6FB3;&#x5927;&#x5229;&#x4E9A;&#x7684;Drupal&#x7F51;&#x7AD9;&#x8BBE;&#x8BA1;&#xFF0C;&#x5F00;&#x53D1;&#x548C;&#x6258;&#x7BA1;&#x4E13;&#x5BB6;</p>
previousnext.md: Content is not part of any section: <p>&#x81EA;2009&#x5E74;&#x4EE5;&#x6765;&#xFF0C;&#x6211;&#x4EEC;&#x5728;&#x6FB3;&#x5927;&#x5229;&#x4E9A;&#x5EFA;&#x7ACB;&#x7684;&#x5927;&#x578B;Drupal&#x7F51;&#x7AD9;&#x6570;&#x91CF;&#x8D85;&#x8FC7;&#x4EFB;&#x4F55;&#x5176;&#x4ED6;&#x516C;&#x53F8;&#xFF0C;&#x5728;&#x5168;&#x7403;&#x4E3A;Drupal 8&#x63D0;&#x4F9B;&#x4EE3;&#x7801;&#x7684;&#x516C;&#x53F8;&#x4E2D;&#x6392;&#x540D;&#x524D;5&#x4F4D;&#x3002;&#x6211;&#x4EEC;&#x7684;&#x77E5;&#x540D;&#x5BA2;&#x6237;&#x5145;&#x5206;&#x5229;&#x7528;&#x4E86;&#x6211;&#x4EEC;&#x5728;&#x7528;&#x6237;&#x4E2D;&#x5FC3;&#x8BBE;&#x8BA1;&#xFF0C;&#x5F00;&#x6E90;&#x8F6F;&#x4EF6;&#x5F00;&#x53D1;&#x548C;&#x6258;&#x7BA1;&#x65B9;&#x9762;&#x7684;&#x80FD;&#x529B;&#x3002;&#x4E91;&#x6258;&#x7BA1;&#xFF0C;&#x5168;&#x90E8;&#x7531;&#x6211;&#x4EEC;&#x5BF9;&#x654F;&#x6377;&#x9879;&#x76EE;&#x4EA4;&#x4ED8;&#x7684;&#x627F;&#x8BFA;&#x652F;&#x6301;&#x3002;</p>

9 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hi @Joy-Hannn 

Can I ask for some context here, as this originally is EN only the checks are failing due to the language. Can you change the headers please?

Also, please remove any HTML - markdown only.

**Comment by dougaitken** [comment]
Resolved in #1063

**Pull request closed without merging**
