### PR TITLE
Add BeyondPricing

### PR DESCRIPTION
**Pull request by OrDuan**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [X] I am an employee of the company mentioned and confirm all included details are correct
- [X] This PR contains housekeeping only (URL edits, copy changes etc)
- [X] You know your alphabet - company is listed in alphabetical order in the README
- [X] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [X] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [X] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [X] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [X] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @OrDuan thanks for the addition:

> USA & Portugal & Worldwide

Can you change this to "Worldwide" please? It is confusing if you list two countries and also worldwide. The region mentioned in the main list is your primary focus for employment.

Once you've changed that, I'll merge it in

**Comment by OrDuan** [comment]
Hey @dougaitken thanks for your comment, 
I changed it to `USA & Worldwide` to line up with other companies format.

Our main office is in USA and we hire worldwide, I hope that clearer now.

**Comment by nylen** [comment]
> Our main office is in USA and we hire worldwide

@OrDuan This is text that should go in the company profile!  It could be as simple as adding "(main office)" next to the entry for your San Francisco office location.

> USA & Worldwide

This doesn't make much sense - by itself it's not enough to make it clear why "USA" would be listed if the company is "Worldwide".  As @dougaitken says, this should just be "Worldwide".

We are far from where we'd like to be with the consistency of the Region fields, but here is our overall plan for how to clean them up:  #485

We are starting with that by trying to ensure better data quality for new changes.

**Comment by OrDuan** [comment]
@nylen Thanks for the clarifications. That totally make sense. 
I updated the location :)

**Pull request merged**
