### PR TITLE
Add new company - Kentik

### PR DESCRIPTION
**Pull request by costasd**
📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here:

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [X] I am an employee of the company mentioned and confirm all included details are correct.
- [X] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [X] The company directly hires employees.
- [X] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [X] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/kentik.md) is included
- [X] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [X] __Region__ details the geographic regions in which this company's employees can reside.
- [X] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Review by dougaitken — CHANGES_REQUESTED** [review]
Can you take a look at the line breaks in this file please?

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Comment by costasd** [comment]
> Can you take a look at the line breaks in this file please?

Thanks for that, should be looking better now!

**Review by dougaitken — APPROVED** [review]

**Comment by dougaitken** [comment]
Thanks for the addition @costasd

**Pull request merged**
