### PR TITLE
Added information for remote jobs at Mediavine

### PR DESCRIPTION
**Pull request by nicolepdev**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @nicolepdev, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 42b1429).  See below for details:

```
mediavine.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
Hi @nicolepdev, you need to add a row for Mediavine to the main README.md file in this same pull request also. Once that's done we'll be happy to add Mediavine.

**Comment by auto-nylen** [comment]
Hi @dougaitken, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 1eb78f9).  See below for details:

```
README.md: Invalid link to company "Mediavine": "company-profiles/mediavine.md"
mediavine.md: No link to company profile from readme

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @dougaitken, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit dc2c0b1).  See below for details:

```
README.md: Invalid link to company "Mediavine": "company-profiles/mediavine.md"
README.md: Broken link to company "Medium": "/company-profiles/medium.md"
mediavine.md: No link to company profile from readme

3 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @dougaitken, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 6bfeeb2).  See below for details:

```
README.md: Broken link to company "Medium": "/company-profiles/medium.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Pull request merged**
