### PR TITLE
Alight Solutions

### PR DESCRIPTION
**Pull request by austinsonger**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [ ] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @austinsonger, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 7c25075).  See below for details:

```
README.md: Company is listed out of order: "Algorithmia" (should be before "Alight Solutions")
alightsolutions.md: Expected filename "alight-solutions.md" for company "Alight Solutions"

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @austinsonger, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit d2a1b13).  See below for details:

```
alightsolutions.md: Expected filename "alight-solutions.md" for company "Alight Solutions"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @austinsonger, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 2cc8fcd). :heavy_check_mark:

**Comment by auto-nylen** [comment]
Hi @austinsonger, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit a542ae0).  See below for details:

```
fetlife.md: Invalid section: "How to Apply".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
fetlife.md: Empty section: "How to Apply". Fill it in or leave it out instead.
fetlife.md: Profile looks complete, but the main readme contains a warning emoji.

3 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @austinsonger, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0f2ebe4).  See below for details:

```
fetlife.md: Invalid section: "How to Apply".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
fetlife.md: Profile looks complete, but the main readme contains a warning emoji.

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hush @auto-nylen, clearly you don't like capitalization. 

(Looks like it's picky @nylen - `apply` vs `Apply` ). 

I'm pushing this through and will fix the emoji for fetlife later

**Comment by nylen** [comment]
>(Looks like it's picky @nylen - apply vs Apply ).

This is on purpose, because otherwise it is going to be inconsistent across files, and this is kind of annoying to correct for in code.  I'll fix it in a separate PR.

**Pull request merged**
