### PR TITLE
Add new company - Quora

### LINKED ISSUE #1139: Add Quora
quora

Quora announced that starting June 2020 it would be a remote-first company which can also be found on their official website.
Does this qualify it for the list? If so, may I create a pull request for it?

### PR DESCRIPTION
**Pull request by codingknite**
Add New Company - [QUORA](https://www.quora.com/)

Closed #1139 

If updating or adding a company, please include details here: _delete this and add details_

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] I am an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. 
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Comment by dougaitken** [comment]
Hey @codingknite - can you walk me through what you've done to the readme file, please? The PR is saying the whole file has changed but previewing it looks as expected?

**Comment by dougaitken** [comment]
Hey @codingknite - can you have a look through the PR and let me know what happened to the readme? It looks like you've changed the formatting as the PR shows me the complete file has changed?

**Comment by codingknite** [comment]
OMG! All I did was add Quora. But looking at the PR I think I know what happened.
I have prettier installed and I can see that the formatting of the whole doc was changed.
I think that happened on save. I will correct it immediately.

**Comment by dougaitken** [comment]
Thanks @codingknite - ping me here when you've pushed the change, thanks. I know the readme isn't the prettiest but reworking that is another day.

**Pull request merged**
