### PR TITLE
Add new company - Cloudapp 

### PR DESCRIPTION
**Pull request by AnuragRoy485**
Signed-off-by: Anurag Roy <anuragroy485@gmail.com>

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] I am an employee of the company mentioned and confirm all included details are correct.
- [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/tree/main/.github/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/tree/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by dougaitken** [comment]
@AnuragRoy485 Don't just tick the boxes in the readme without reading what they say.

If you're editing the readme, please ensure you edit any related readme files. Thanks.

**Comment by AnuragRoy485** [comment]
Yea I have edited the readme,not added any company.

**Comment by dougaitken** [comment]
@AnuragRoy485 Cloudapp now matches the region in the company profile but you've changed Continu to `Worldwide` but the read me file - https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/continu.md#region - shows `USA`. 

Your PR template didn't explain any of your contributions, it's not helpful.

I've looked into this, [Continu](https://jobs.lever.co/Continu) only hires within the USA so please edit your `Worldwide` edition back to `USA`. Thanks.

**Comment by dougaitken** [comment]
Closing - CloudApp is now Zight. And Continu don't have opening to check.

**Pull request closed without merging**
