### PR TITLE
added information to Delighted

### PR DESCRIPTION
**Pull request by anangnovriadi**
# Delighted

## Company blurb

We’re constantly on the lookout for extremely talented people to join our team. Delighted is deeply committed to helping companies improve the experiences of their customers. It’s a mission we don’t take lightly and we’re looking for people who share that passion. If you’re great at what you do, we’d love to chat!

## Company size

1 - 50

## Remote status

We’re 100% remote. You’ll have the flexibility to work from home or rent a personal office, and set your own schedule.

## Region

Worldwide. While our management team is based in the US, we hire technical writers all around the world.

## Company technologies

Software Development:

JavaScript
Golang
Python
PHP
Java
.NET
Ruby
Mobile apps
Microservices
Agile methodology
Engineering management
DevOps:

AWS
Azure
Heroku
CI/CD
Docker
Kubernetes
Databases
Monitoring

## Office locations

1027 Alma St
Palo Alto, California, US

## How to apply

Check our jobs page: https://delighted.com/jobs/

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @sinAshish, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 2060629).  See below for details:

```
kaggle.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @sinAshish, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 5b4b8d4).  See below for details:

```
README.md: Missing company profile for "Kaggle", or broken link: "/company-profiles/Kaggle.md"
kaggle.md: No link to company profile from readme

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @TanishqDsharma, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 3a186aa). :heavy_check_mark:

**Comment by dougaitken** [comment]
I'm not sure what is happening here @anangnovriadi but can you start again, please?

**Pull request closed without merging**
