### PR TITLE
Removed worldwide for Kodify

### PR DESCRIPTION
**Pull request by zafar-saleem**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [ ] You know your alphabet - company is listed in alphabetical order in the README
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by nylen** [comment]
@zafar-saleem I think "EU & Worldwide" is correct, at least according to the [Kodify company profile](https://remoteintech.company/kodify/):

>Company is based in Barcelona, Spain but you can work from everywhere

Do you have any more details about this change?

**Comment by auto-nylen** [comment]
Hi @zafar-saleem, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 6189e67).  See below for details:

```
acquia.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
@zafar-saleem

>Removed Acquia from the list
>
>Remove Acquia from the list because none of the jobs posted on their career page mentioned remote, all of them are onsite.

1. This change would need to go in a separate PR

2. This is not correct anyway. On https://www.acquia.com/careers/open-positions there are not a lot of remote jobs but there are some:

2020-03-07T03-35-29Z

**Comment by zafar-saleem** [comment]
> Hi @zafar-saleem, thanks for your contribution!
> 
> Our automated checks detected some problems with this pull request (as of commit [6189e67](https://github.com/remoteintech/remote-jobs/commit/6189e67a29a1f43f9f05cf26dc5d9235ab031445)). See below for details:
> 
> ```
> acquia.md: No link to company profile from readme
> 
> 1 problem detected
> ```
> 
> Please fix these issues and push a new commit to this pull request.

I see there is a link to company profile in this request.

**Comment by dougaitken** [comment]
Hey @zafar-saleem you removed Acquia from the main list - is there a reason for that or can we revert that change?

**Comment by zafar-saleem** [comment]
> Hey @zafar-saleem you removed Acquia from the main list - is there a reason for that or can we revert that change?

As the remote jobs posted on their career page specifically in US so I believe that should be mentioned in the list alongside company's name.

**Comment by dougaitken** [comment]
@zafar-saleem That wasn't the change you made, rather than edit the line for `Acquia` you deleted the line. 

To confirm - this commit - https://github.com/remoteintech/remote-jobs/pull/733/commits/6189e67a29a1f43f9f05cf26dc5d9235ab031445

Can you change that edit to add Acquia back and change Worldwide to US if you can confirm they only hire in the US

**Comment by zafar-saleem** [comment]
> @zafar-saleem That wasn't the change you made, rather than edit the line for `Acquia` you deleted the line.
> 
> To confirm - this commit - [6189e67](https://github.com/remoteintech/remote-jobs/commit/6189e67a29a1f43f9f05cf26dc5d9235ab031445)
> 
> Can you change that edit to add Acquia back and change Worldwide to US if you can confirm they only hire in the US

@dougaitken do you want me to make above change as you mentioned and create another pull request?

**Comment by dougaitken** [comment]
Can you commit again to this PR, please? @zafar-saleem

**Comment by nylen** [comment]
This question also still needs an answer:

> @zafar-saleem I think "EU & Worldwide" is correct, at least according to the [Kodify company profile](https://remoteintech.company/kodify/):
> 
> > Company is based in Barcelona, Spain but you can work from everywhere
> 
> Do you have any more details about this change?

**Comment by nylen** [comment]
Closing, no response for a while and this change looks incorrect anyway.

**Pull request closed without merging**
