### PR TITLE
add new company - Netlify

### PR DESCRIPTION
**Pull request by prankush-tech**
Signed-off-by: Prankush Giri <76916192+prankush-tech@users.noreply.github.com>

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [x] I am an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/tree/main/.github/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/tree/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by dougaitken** [comment]
Would you be able to add a company-profile.md file as well please? This is required for initial contributions as mentioned in the Pull Request template. Thanks!

**Comment by prankush-tech** [comment]
# NETLIFY

Netlify is the fastest way to build the fastest sites. Used by more than 800,000 web developers and businesses, the Netlify platform provides modern build workflows, serverless functions and a global Application Delivery Network to deliver the most performant, secure and scalable websites and applications.

# How to Apply 

You can visit https://www.netlify.com/careers/ and apply for positions in thei team.


# What if you need an accommodation for the interview?
No problem! If you need accommodations for the interviews, please let your recruiter know or contact accommodations@netlify.com

**Comment by dougaitken** [comment]
@prankush-tech please review the company profile template and model that. The structure of the file is required. Thanks

**Comment by prankush-tech** [comment]
I have reviewed the company profile template and model that.

**Comment by prankush-tech** [comment]
# NETLIFY

## Company blurb
Netlify is the fastest way to build the fastest sites. Used by more than 800,000 web developers and businesses, the Netlify platform provides modern build workflows, serverless functions and a global Application Delivery Network to deliver the most performant, secure and scalable websites and applications.



## Company size
251-500 (as of Aug 30, 2022)


## Remote status
At Netlify, we have a distributed culture rather than just being "remote-friendly." Simply put, we strive to be a workplace where you can work from home and have an equal opportunity to influence decisions and culture across the organization. We tackle complex problems, in a remote first environment while caring deeply about what we do and having fun.

## Region
Current openings are for remote positions in US, UK.


## Company technologies
Jamstack React Next.js Vue.js Svelte Gatsby Nuxt Sitecore Drupal WordPress

## Office locations
Netlify is a distributed company. We work remotely and bring team members together on occasion around the world and in our home base in San Francisco

# How to Apply 

You can visit https://www.netlify.com/careers/ and apply for positions in thei team.
What if you need an accommodation for the interview?
No problem! If you need accommodations for the interviews, please let your recruiter know or contact accommodations@netlify.com

**Pull request closed without merging**
