### PR TITLE
Add instamobile reference

### PR DESCRIPTION
**Pull request by amandeepmittal**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @amandeepmittal, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit ada5914).  See below for details:

```
README.md: Broken link to company "Instamobile": "/company-profiles/instamobile.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
Hi @amandeepmittal, you need to add a company profile for Instamobile according to our [contributing guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

The website link you've included in the main readme also doesn't work because it's misspelled.

**Comment by amandeepmittal** [comment]
Hi @nylen, I am sorry about it. Let me amend my mistake.

**Comment by auto-nylen** [comment]
Hi @amandeepmittal, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 13f13a4).  See below for details:

```
instamobile.md: Profile looks incomplete, but the main readme does not contain a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @amandeepmittal, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit fe9ab30). :heavy_check_mark:

**Comment by nylen** [comment]
@amandeepmittal we require a company profile with **completed information** for all new submissions. This should follow the template of our example profile: https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md

You don't need to include every single section, but at least a bit of info about what the company does and where they accept job applicants from.

**Comment by amandeepmittal** [comment]
@nylen Thanks for the info. I do have some information but was missing few points like company size and so on. I will update the profile.

**Comment by auto-nylen** [comment]
Hi @amandeepmittal, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 98f23f5).  See below for details:

```
instamobile.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @amandeepmittal, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 37a5181). :heavy_check_mark:

**Pull request merged**
