### PR TITLE
Add MailerLite to the list

### PR DESCRIPTION
**Pull request by pstoncius**
Add mailerlite.md to the list of remote companies.

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @pstoncius, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 4a9617c).  See below for details:

```
mailerlite.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
^ I just fixed our review bot. As it said above, please add a row for this company to the main readme, and then we can merge this.

**Comment by pstoncius** [comment]
hi @nylen, thank you! I just added a row to the main readme.

**Comment by nylen** [comment]
I don't see any new commits. Did you forget to push your changes?

**Comment by nylen** [comment]
Nevermind, I see #731 now. These changes need to be done in the same PR instead of being split across 2 different PRs.

**Pull request closed without merging**
