### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by snehaj27**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [Y] I am an employee of the company mentioned and confirm all included details are correct
- [ Y] This PR contains housekeeping only (URL edits, copy changes etc)
- [Y] You know your alphabet - company is listed in alphabetical order in the README
- [Y] The company directly hires employees. No bootcamps / freelance sites / etc
- [Y] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [Y] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [Y] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [Y] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [Y] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @snehaj27, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit edd1815).  See below for details:

```
README.md: Missing company profile for "Design+code", or broken link: "/company-profiles/designcode.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hi @snehaj27 can you add some details on a company profile please?

**Comment by snehaj27** [comment]
> Hi @snehaj27 can you add some details on a company profile please?

Ya right! 
Please go through my new commits to this pull request.

**Comment by dougaitken** [comment]
Please revert the deletion of the example company - that should never be removed @snehaj27

**Pull request closed without merging**
