### PR TITLE
Add Theorem

### PR DESCRIPTION
**Pull request by fsaravia**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am a full time contractor of the company mentioned and confirm all included details are correct
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees and full time independent contractors. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @fsaravia, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 1bbb367).  See below for details:

```
theorem.md: Invalid section: "Company Size".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
theorem.md: Invalid section: "Remote Status".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
theorem.md: Invalid section: "Company Technologies".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
theorem.md: Invalid section: "Office Locations".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
theorem.md: Required section "Company blurb" not found.
theorem.md: Content is not part of any section: <p>Do you enjoy collaborating in a consultative environment and guiding people using best practices to achieve great results? Do you want to influence and contribute to the growth of a high performing, quality focused team? If so, <a href="https://theorem.co">Theorem</a> wants to know more about you!</p>
theorem.md: Content is not part of any section: <p><a href="https://theorem.co">Theorem</a> is a software consultancy that believes in simplicity in software design. We deliver solutions for startups and enterprises - You can see our <a href="https://theorem.co/portfolio">portfolio</a> to learn more about the results we&apos;ve delivered for our clients.</p>

7 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @fsaravia, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 0db0e34). :heavy_check_mark:

**Comment by dougaitken** [comment]
Cheers for the contribution, @fsaravia

**Comment by fsaravia** [comment]
Thanks for the quick merge!

**Pull request merged**
