### PR TITLE
Add Grubhub

### PR DESCRIPTION
**Pull request by wakingrufus**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] Any missing parts from the profile, please use `<Unknown>` to allow for future completion
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @wakingrufus, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit 1a7ca1d).  See below for details:

```
grubhub.md: Expected filename "github.md" for company "GitHub"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @wakingrufus, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit d2b36a3). :white_check_mark:

**Comment by dougaitken** [comment]
Nice one! Thanks @wakingrufus

**Comment by brianguertin** [comment]
Hmm, I did not find them to be remote friendly. I left the company largely because they were not interested in remote workers. I’m based in Boston.

**Comment by wakingrufus** [comment]
Yes, teams are remote or colocated, not mixed. Also remote teams are new, only being established within the last year.

**Comment by dougaitken** [comment]
@brianguertin are you able to add a timescale? This sort of feedback is good within context. 
"They weren't open to remote jobs... 5 years ago", right? 

Thanks for the clarification @wakingrufus

**Comment by brianguertin** [comment]
I think @wakingrufus said it best. most teams are colocated, but some teams are starting to allow remote. I left this month from one of the mobile app dev teams, which I believe are all colocated.

Looking at their current listings, there is 1 "remote" opening out of about 30 tech openings: https://careers-grubhub.icims.com/jobs/search?pr=1&searchCategory=24631&schemaId=&o=

**Pull request merged**
