### PR TITLE
Add iosapptemplates.com jobs

### PR DESCRIPTION
**Pull request by mrcflorian**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @mrcflorian, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 91f9929).  See below for details:

```
README.md: Company is listed out of order: "iOS App Templates" (should be before "IPS Group, Inc.")
iosapptemplates.md: Company title "iOS App Templates" doesn't match filename (expected ~ "ios-app-templates.md")
iosapptemplates.md: Invalid section: "Build iOS apps faster".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
iosapptemplates.md: Invalid section: "2 employees".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
iosapptemplates.md: Required section "Company blurb" not found.

5 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @mrcflorian, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit a36e5a1).  See below for details:

```
iosapptemplates.md: Company title "iOS App Templates" doesn't match filename (expected ~ "ios-app-templates.md")
iosapptemplates.md: Invalid section: "Build iOS apps faster".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
iosapptemplates.md: Invalid section: "2 employees".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
iosapptemplates.md: Required section "Company blurb" not found.

4 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0d30bd3).  See below for details:

```
README.md: Broken link to company "iOS App Templates": "/company-profiles/iosapptemplates.md"
ios-app-templates.md: No link to company profile from readme

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit e0d5413). :heavy_check_mark:

**Comment by nylen** [comment]
Thanks for adding iOS App Templates.  I've fixed the outstanding issues in this pull request, just waiting for the :robot: to confirm and I'll merge this PR.

**Pull request merged**
