### PR TITLE
Add Hotjar information

### PR DESCRIPTION
**Pull request by scott-w**
Added information for Hotjar from the recruitment team. I've included this information on behalf of the recruitment team at Hotjar.

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @scott-w, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0597f08).  See below for details:

```
hotjar.md: Invalid section: "Company Size".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
hotjar.md: Invalid section: "Remote Status".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
hotjar.md: Invalid section: "Company Technologies".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
hotjar.md: Invalid section: "Office Locations".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
hotjar.md: Profile looks complete, but the main readme contains a warning emoji.

5 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @scott-w, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit cdd913b).  See below for details:

```
hotjar.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @scott-w, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 2944dca). :heavy_check_mark:

**Comment by nylen** [comment]
Excellent, thanks for the update!

**Pull request merged**
