### PR TITLE
Adding Favicon

### PR DESCRIPTION
**Pull request by dougaitken**
Adding a favicon.

Gonna request a review since I didn't preview this locally - still need to set that up. 

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] This PR contains housekeeping only (URL edits, copy changes etc)

Also, didn't remove the previous PR. this might cause problems ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by dougaitken** [comment]
dramafever references #504 

I added the favicon and referenced it in `base.html`

**Comment by dougaitken** [comment]
Closes #461

**Comment by nylen** [comment]
For future reference here is how you see the preview once you have the PR on GitHub:

> 

> 

In this case the preview URL is https://deploy-preview-505--remote-jobs.netlify.com/

The favicon is not showing up there because it needs to be copied to the site build folder.  This is a bit different than the way existing files are copied (they include a "cache buster" string in the filename), so I'll finish this PR.

**Comment by nylen** [comment]
Also, I think adding a favicon is not so straightforward.

- [This Stackoverflow answer](https://stackoverflow.com/a/25961390/106302) says that the method used here is deprecated and only works on older versions of IE.
- I've used [this favicon generator site](https://realfavicongenerator.net/) successfully in the past.  We can plug the image in there.
- That generator site does a good bit more than just add a file and a `link` tag.   [Here's an example](https://github.com/nylen/nylen.io/commit/057c0ea68187ba44e4fb9c496f54e677c2c77283) of what it generates.

**Comment by edelstone** [comment]
Yeah I've used that favicon generator a bunch and it's proven to be pretty solid.

**Comment by dougaitken** [comment]
To be honest, I think I need a new favicon. The one on the blog is a gif I whipped up in 2mins to use on GitHub 😂 
[favicon_package_v0.16.zip](https://github.com/remoteintech/remote-jobs/files/2534397/favicon_package_v0.16.zip)

Here is the package I generated using the original icon

**Comment by dougaitken** [comment]
@edelstone if you're volunteering, I'm hope to anything. 🎉

**Comment by edelstone** [comment]
Here's a few options. Let me know what you think.

pin-wifi-square
pin-wifi
wifi-square

**Comment by edelstone** [comment]
Here's a zip with the Sketch file, and SVG/PNG of each.

[remote-jobs-favicon.zip](https://github.com/remoteintech/remote-jobs/files/2542541/remote-jobs-favicon.zip)

**Comment by nylen** [comment]
screen shot 2018-11-02 at 7 55 39 am

This one is definitely my favorite.  I think with the other two it's hard to tell what the "map marker" icon is at small scale.

I'm happy with this one, but I wouldn't mind seeing what it looks like inverted either (transparent background, red wifi symbol).

**Comment by edelstone** [comment]
wifi

**Comment by nylen** [comment]
I dig it.  I think that's the one.

**Comment by edelstone** [comment]
Here's a `.zip` with the Sketch file, just so you have everything for future needs. Feel free to use these wherever.

[remote-jobs-favicon.zip](https://github.com/remoteintech/remote-jobs/files/2546752/remote-jobs-favicon.zip)

**Comment by dougaitken** [comment]
@nylen you want to take this one since you have experience of integrating it previously. I'll lurk your changes so I understand the addition

**Comment by dougaitken** [comment]
Also, thanks so much for the contribution @edelstone !

**Comment by nylen** [comment]
Sure, I'll finish this PR "soon" and we can leave it open until then.

As far as the other changes, I'm going to plug that image into the favicon generator we were talking about above. That's easy, what is probably not so obvious is how to get the files copied to the right place.

**Comment by nylen** [comment]
Done!  Thanks @edelstone for the nice icon and @dougaitken for getting this started.

**Comment by dougaitken** [comment]
Cheers for doing this, @nylen!

**Pull request merged**
