### PR TITLE
Add continued and ApproveMe

### PR DESCRIPTION
**Pull request by jhonnrodr**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @jhonnrodr, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit d3c72d8).  See below for details:

```
README.md: Company is listed out of order: "ConsenSys" (should be before "Continued")

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @jhonnrodr, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit bca6658). :heavy_check_mark:

**Comment by auto-nylen** [comment]
Hi @jhonnrodr, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 2f4f347).  See below for details:

```
README.md: Missing company profile for "ApproveMe", or broken link: "/company-profiles/approveme.md"
README.md: Company is listed out of order: "apartment therapy" (should be before "ApproveMe")

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @jhonnrodr, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit ec87f68).  See below for details:

```
README.md: Company is listed out of order: "apartment therapy" (should be before "ApproveMe")

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @jhonnrodr, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 282098a). :heavy_check_mark:

**Comment by dougaitken** [comment]
Hi @jhonnrodr

I’d prefer if companies were added to the list with a full company profile rather than adding just the name. Are you able to add more details to those two please?

**Comment by nylen** [comment]
Closing due to inactivity. Anyone is welcome to submit a new PR for these companies (though it's better to do 1 company at a time).

**Pull request closed without merging**
