### PR TITLE
Add Scopic Software to the list

### PR DESCRIPTION
**Pull request by marinehb**
Let's have Scopic Software, the world's largest virtual company in the list!

_Company blurb_
Custom solutions for virtually everything. The world’s largest virtual company. We create custom solutions for virtually everything! Our passion is developing visually engaging and interactive solutions, custom made to enhance your business. Over a decade of service and 1000+ projects, developing digital products and user-centric software for a wide range of industries and niches including: Manufacturing, Music and film, Fintech, Food and Fitness, Healthcare and Gaming.

_Company size_
200+ number of Scopic team members.

_Remote status_
We are a fully remote company, with our team member located in 30+ countries.

_Company technologies_
WEB FRAMEWORKS
We turbocharge our development process with state of the art frameworks such as Yii, Django, Symfony, Spring, Java and Node.js.

RESPONSIVE DESIGN
At Scopic we believe it’s not about the size but what you do with it. With technologies like Bootstrap and LESS, there’s not a screen size we don’t love.

NATIVE/CROSS-PLATFORM SDKS
We’re not tied down by a single platform; we like to play the field. We use Xamarin, AdobeAIR, PhoneGAP and Qt to cater to different operating systems.

OPENGL, DIRECT3D
We are experts in standard 3D design. We utilize computer vision libraries such as OpenGL, OpenCV and DirectD3.

SQL AND NOSQL DATABASES
Scopic has a foot in both worlds. We use tried and true SQL when the fit is right, but aren’t afraid to delve into newer technologies like Hadoop, MongoDB, Dynamo and other applications for big data.

_How to apply_
https://scopicsoftware.com/careers/

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @marinehb, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0b5bc61).  See below for details:

```
README.md: Company is listed out of order: "Scopic Software" (should be before "Scrapinghub")
README.md: Broken link to company "Scopic Software": "/company-profiles/scopicsoftware.md"

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @marinehb, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0a106bf).  See below for details:

```
README.md: Broken link to company "Scopic Software": "/company-profiles/scopic-software.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @marinehb, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 4379f2e).  See below for details:

```
scopic-software.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
Hi @marinehb 

> The world’s largest virtual company.

How is this true?  I think this statement should probably be removed, as I can name several larger remote-only companies without looking at the list.

Also just an administrative note - this PR will close issue #518 when it's finished.

**Comment by marinehb** [comment]
Hi @nylen,

Thanks for getting back to me in this.

I am sorry, it should be the world's largest virtual software company. It is my mistake.

Thanks,
Marine

**Comment by nylen** [comment]
Ah, I see.  I was thinking that **virtual** meant **remote**.

Would it be more accurate / OK to say **virtual reality** instead?

If not, I am fine to leave this as-is, but I think it will probably also be confusing to others who read it.

**Comment by marinehb** [comment]
Hi @nylen,

Virtual does mean remote. We are the largest virtual software company in the world. We are a fully remote company and we offer software development as a service, while other larger virtual companies don't.

**Comment by nylen** [comment]
OK - that's how I was originally reading this.  I think it is safe to say that Scopic is not the largest distributed custom software development company or agency in the world.

**Comment by dougaitken** [comment]
> Virtual does mean remote. We are the largest virtual software company in the world. We are a fully remote company and we offer software development as a service, while other larger virtual companies don't.

I'd recommend not using this type of claim please @marinehb 

There are software companies who are remote which have many more employees than Scopic. Let's leave that part out of the description 😄

**Comment by nylen** [comment]
I've updated the PR to remove this wording.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 8032243). :heavy_check_mark:

**Pull request merged**
