### PR TITLE
Broken link fixes Part 1

### LINKED ISSUE #528: Broken links
I've tested broken links using a Google spreadsheets [custom formula](https://medium.com/@the.benhawy/how-to-use-google-spreadsheets-to-check-for-broken-links-1bb0b35c8525), some links need to be fixed:

- Axelerant
Correct URL: https://www.axelerant.com/careers

- Webikon
Correct URL: https://webikon.eu/ (But I can't see any Jobs page there)

### PR DESCRIPTION
**Pull request by rylim**
This Pull Request should adhere to the repository's [Code of Conduct](../../main/.github/CONTRIBUTING.md).

Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]` 

Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: Fix broken links / Remove non-existent companies

Fixes #528 (Partially)

- Remove non-existent company/link
  - colivre
- Fix broken links
  - adaface
  - gorman
  - teamultra
  - canonical
  - mapbox
  - focusnetworks
  - stairlin

Reports from [markdown-link-check](https://github.com/tcort/markdown-link-check)

```
FILE: ./colivre.md
  [✖] http://colivre.coop.br/sobre/
  [✓] mailto:contato@colivre.coop.br

  2 links checked.

  ERROR: 1 dead links found!
  [✖] http://colivre.coop.br/sobre/ → Status: 0

FILE: ./teamultra.md
  [✖] https://www.teamultra.net/contact-us/careers/
  [✓] mailto:careers@teamultra.net

  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.teamultra.net/contact-us/careers/ → Status: 0

FILE: ./adaface.md
  [✓] https://www.adaface.com/pair-pro
  [✖] https://angel.co/company/adaface

  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://angel.co/company/adaface → Status: 403

FILE: ./gorman-health-group.md
  [✖] https://www.gormanhealthgroup.com/careers/

  1 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.gormanhealthgroup.com/careers/ → Status: 0

FILE: ./canonical.md
  [✖] https://ldd.tbe.taleo.net/ldd03/ats/careers/jobSearch.jsp?org=CANONICAL&cws=1&rid=86&org=CANONICAL
  [✓] http://www.canonical.com/careers/all-vacancies

  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://ldd.tbe.taleo.net/ldd03/ats/careers/jobSearch.jsp?org=CANONICAL&cws=1&rid=86&org=CANONICAL → Status: 500

  [✖] https://blog.mapbox.com/how-we-hire-at-mapbox-cd946418299f

  17 links checked.

  ERROR: 1 dead links found!
  [✖] https://blog.mapbox.com/how-we-hire-at-mapbox-cd946418299f → Status: 410

FILE: ./focusnetworks.md
  [✖] https://www.linkedin.com/company/focusnetworks-interactive/
  [✓] https://focusnetworks.enlizt.me/?utm_source=jooble&utm_medium=cpc&utm_campaign=jooble

  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.linkedin.com/company/focusnetworks-interactive/ → Status: 999

FILE: ./stairlin.md
  [✖] https://github.com/stairlin/lego
  [✖] https://www.stairlin.com/jobs.html

  2 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/stairlin/lego → Status: 404
  [✖] https://www.stairlin.com/jobs.html → Status: 404
```

Check off this list as appropriate (add an `x` between the `[]`). It will be used by @dougaitken when reviewing your contribution.

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**

This is a modified version of the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by KieranRobson — APPROVED** [review]

**Comment by rylim** [comment]
Thanks @KieranRobson! Could you help to merge this PR since I don't have write access to it?

**Comment by dougaitken** [comment]
It'll get merged soon @rylim don't worry. I appreciate your contributions. 

Only I have merge/write access and I personally have a lot on personally right now.

**Review by dougaitken — APPROVED** [review]

**Comment by dougaitken** [comment]
Gorman and team ultra will need proper updates if they've changed company/names or whatever but this is great for now, thanks @rylim 

This will close #528 but I'm happy with that. I do want to move towards some regular link checker anyway which will eventually fix this completely.

**Comment by rylim** [comment]
@dougaitken totally understandable and thank you!

**Pull request merged**
