### PR TITLE
edit 38 listed companies'

### PR DESCRIPTION
**Pull request by Hopelezz**
📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.

If updating or adding a company, please include details here:

- 1password
- 15five
- abiturma
- acct
- activecampaign
- adaface
- addstructure
- aerolab
- aestudio
- agflow
- aha
- aim-india
- airgarage
- airtreks
- aivitex  : add office location, site link was broken. Previous site address <https://en.aivitex.de/> Current site address <https://aivitex.com/en>
- alice
- algorand
- alight-solutions
- alley
- alphasights
- and-yet
- andela
- animalz
- appwrite
- argyle : updated website address. was <https://register.rippling-ats.com/register/cancelled> Current <https://argyle.com/careers#open-positions>, Office location had typo : USAus changed to USA
- ark.io
- artefactual
- audiense
- aula
- auth0
- axios
- balena
- balsamiq
- bandlab
- bear-group
- bebanjo
- beenverified
- betable

Updates include :

- MD001/heading-increment/header-increment: Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
- MD009/no-trailing-spaces: Trailing spaces [Expected: 0 or 2; Actual: 1]
- MD012/no-multiple-blanks: Multiple consecutive blank lines [Expected: 1; Actual: 2]
- MD022/blanks-around-headings/blanks-around-headers: Headings should be surrounded by blank lines
- MD032/blanks-around-lists: Lists should be surrounded by blank lines
- MD034/no-bare-urls: Bare URL used
- agflow.md : Illegal tag name. Use '&lt;' to print '<'.
- MD036/no-emphasis-as-heading/no-emphasis-as-header: Emphasis used instead of a heading

### CODE REVIEW

**Comment by Hopelezz** [comment]
Hello all,

This is my first time submitting to an open-source project. I appreciate the effort being placed on this project and want to contribute to it. I found some errors based on the Markdown guidelines set by [DavidAnson](https://github.com/DavidAnson). There were a few broken links as indicated, and even added office location based on one of the company's web pages. 

I plan to do more should this go through. If there are any corrections to my submission, please let me know and I'll be happy to help.

ps. you might have to disregard my edit to the PULL_REQUEST_TEMPLATE.MD since this is where I logged my progress.

**Comment by dougaitken** [comment]
Hi @Hopelezz I appreciate the enthusiasm here!

For code review, can I ask you to split this into multiple PRs? 

* updates
* additions
* formatting etc

The reason I ask is this I don't want to block company updates or additions when reviewing such a big change with the formatting.

Thanks!

**Comment by dougaitken** [comment]
Also, can you link directly to the standards or whatever you're referring to, please?

**Comment by Hopelezz** [comment]
> Hi @Hopelezz I appreciate the enthusiasm here!
> 
> For code review, can I ask you to split this into multiple PRs? 
> 
> * updates
> * additions
> * formatting etc
> 
> The reason I ask is this I don't want to block company updates or additions when reviewing such a big change with the formatting.
> 
> Thanks!

How do I go about doing  this? Are these just different commits as the edits are done? 

Also the other day I realized that this branch said "stale" should I have been working on the main? If I'm going to have to do any rework should I start from there instead?

Happy to help on the project. 
Any chance we could have a voice/video chat and discuss some of the points here?

As for the markdown lint:
https://github.com/DavidAnson/markdownlint

**Comment by dougaitken** [comment]
Hey @Hopelezz ah yes! Sorry I didn't even check that! Yes, you should be forking the repo, then branching `main` then opening a PR from there. I haven't setup multiple branches or such yet.

I think the best thing to do now would be to create branches based on each feature you're focusing on. 

Happy to go over this async ideally but if it would help you, we can have a call some point. Email `remote at dougaitken dot co for uk`. FYI, I'm based in the UK.

**Comment by dougaitken** [comment]
@Hopelezz Are you still looking to contribute here?

**Comment by dougaitken** [comment]
@Hopelezz 

Let me know if you want to work on something like this again

**Pull request closed without merging**
