### PR TITLE
Create XWP.md

### PR DESCRIPTION
**Pull request by Akshra2020**
Signed-off-by: Akshra <81403230+Akshra2020@users.noreply.github.com>

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] I am an employee of the company mentioned and confirm all included details are correct.
- [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/tree/main/.github/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/tree/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Akshra2020** [comment]
Sir why its failling

**Comment by dougaitken** [comment]
Hey @Akshra2020 

> Sir why its failling

The reason is related to this checklist item you checked on the Pull Request template but you haven't done:

> company is listed in alphabetical order in the README.md file.

You need to edit this file, in the same Pull Request, then commit that.

Please handle this, and once merged I'll close off the other failed PRs

**Comment by dougaitken** [comment]
#1494 #1497

**Comment by Akshra2020** [comment]
Okay thank you so much
I will edit it soon and let you know
Sorry for the inconvenience
Thanks a lot for connecting

**Comment by dougaitken** [comment]
@Akshra2020 The readme edit and the company profile need to be part of the same Pull Request. Make sure you're on the same branch when making the change then commit your edits to that Pull Request.

**Pull request closed without merging**
