### PR TITLE
Adding info for O'Reilly Media

### PR DESCRIPTION
**Pull request by droidenator**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Can you include some details about remote status and such @droidenator - I've noticed a few of your edits don't have that and as this whole project is focused on "remote" this is an important part of the company profile.

**Comment by auto-nylen** [comment]
Hi @droidenator, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 46e4ab0).  See below for details:

```
oreilly-media.md: Invalid section: "Remote Status".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @droidenator, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit bf0f6f6). :heavy_check_mark:

**Comment by droidenator** [comment]
@dougaitken This is about the best I could find regarding their remote status. I didn't include that info in other edits I submitted unless the sites prominently featured it.

**Comment by dougaitken** [comment]
Ideally we'd have a region but I'll push this in for now

**Comment by droidenator** [comment]
@dougaitken That was another one I wasn't sure about. O'Reilly lists offices all over the world but doesn't explicitly say if they only hire US for most positions. Sorry I couldn't get a more clear answer here.

**Pull request merged**
