### PR TITLE
Update upworthy.md

### PR DESCRIPTION
**Pull request by dt170**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @dt170, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0da533e).  See below for details:

```
upworthy.md: Expected 1 first-level heading but found 2
upworthy.md: Duplicate section: "Company blurb".
upworthy.md: Profile looks complete, but the main readme contains a warning emoji.

3 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dt170** [comment]
Can you please tell me whats wrong? so I will fix the issue

**Comment by dt170** [comment]
How can i fix this issue ? upworthy.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected

**Comment by KolibaEast** [comment]
I get tons of emails from the community.  I dont want that

Von meinem iPhone gesendet

**Comment by auto-nylen** [comment]
Hi @dt170, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 8558743). :heavy_check_mark:

**Comment by dougaitken** [comment]
@KolibaEast I'm unsure how you're getting these but at the bottom of any email from GitHub there will be an unsubscribe link.

**Comment by dougaitken** [comment]
Hey @dt170 can you make the readme only "Worldwide" and remove the timezone but add the timezone with clarification to the company profile, please?

**Comment by dt170** [comment]
> Hey @dt170 can you make the readme only "Worldwide" and remove the timezone but add the timezone with clarification to the company profile, please?

Fixed as requasted have a great day !

**Pull request merged**
