### PR TITLE
Update charity-water.md

### PR DESCRIPTION
**Pull request by nityaoberoi**
Added information regarding our organization, details regarding our culture / open positions

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [X] I am an employee of the company mentioned and confirm all included details are correct
- [X] This PR contains housekeeping only (URL edits, copy changes etc)
- [X] You know your alphabet - company is listed in alphabetical order in the README
- [X] The company directly hires employees. No bootcamps / freelance sites / etc
- [X] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [X] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [X] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [X] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [X] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @nityaoberoi, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0618c71).  See below for details:

```
charity-water.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hey @nityaoberoi - thanks for this contribution!

Can you update the main readme file and remove the ⚠️ from beside the company name, please? 

Thanks,

**Comment by auto-nylen** [comment]
Hi @nityaoberoi, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit a074da4). :heavy_check_mark:

**Comment by dougaitken** [comment]
Thanks @nityaoberoi!

**Pull request merged**
