### PR TITLE
Added New Company Fleetio

### PR DESCRIPTION
**Pull request by VishalAggarwal2**
* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by VishalAggarwal2** [comment]
@dougaitken  please merge this pull request for the hactoberfest 2023

**Comment by KieranRobson** [comment]
@VishalAggarwal2 Please be patient, this has not even been reviewed yet.

**Comment by dougaitken** [comment]
There's no rush @VishalAggarwal2  you still have 2 weeks. I've set the checks to run, but I think they fail so you'll need to fix your submission to pass.

**Comment by VishalAggarwal2** [comment]
@dougaitken  can you explain what was the issue in my pull request

**Comment by dougaitken** [comment]
@VishalAggarwal2 The literal file name needs to be all in lowercase, not a capital letter at the start, so rename the file `fleetio.md`, NOT `Fleetio.md`.

**Comment by VishalAggarwal2** [comment]
@dougaitken 
Thanks 
I change the name of the file I there is any other issue please let me know

**Review by dougaitken — APPROVED** [review]

**Comment by VishalAggarwal2** [comment]
@dougaitken  thanks sir

**Pull request merged**
