### PR TITLE
Update peopledoc

### PR DESCRIPTION
**Pull request by kaconk17**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @kaconk17, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 3e2a420).  See below for details:

```
peopledoc.md: Empty section: "Company size". Fill it in or leave it out instead.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @kaconk17, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 170764a). :heavy_check_mark:

**Comment by dougaitken** [comment]
Hi @kaconk17 this is more than one company - can you detail what changes have been made, please?

**Comment by kaconk17** [comment]
Hi @dougaitken I updated peopledoc

**Comment by dougaitken** [comment]
Looking at the changes in this PR you didn't just change one company @kaconk17

**Comment by kaconk17** [comment]
@dougaitken sorry but i mean only commit 02f191d & 79d69e7, please pick these commits only

**Comment by dougaitken** [comment]
Are you able to do anything else with this please @kaconk17 

If you can start again and only include one company per PR, I'll mark this as an accepted PR.

**Comment by kaconk17** [comment]
HI @dougaitken I am very sorry, to fix this PR I have create new PR : https://github.com/remoteintech/remote-jobs/pull/1033

**Pull request closed without merging**
