### PR TITLE
Add full profile search

### LINKED ISSUE #462: Add a filter for "needs more info"
(to the table at https://remoteintech.company/)

This should allow displaying companies that have profiles which are "complete" (not marked with :warning:) or "incomplete" (marked with :warning:).

### LINKED ISSUE #584: Expand the Search scope to all of the profile rather than name and region
Related to #569 

Currently, when someone wants to search the list, they are limited to name and region. Having the ability to search the whole profile would allow for filtering by technology or another keyword.

### PR DESCRIPTION
**Pull request by nylen**
This pull request modifies the "filter" box on the list homepage to search through all company profile data.

You can read more about how the search works here: https://blog.remoteintech.company/search-help/ This page is also linked from the "More info" text at the search box.

- Closes #584
- Closes #462 (search for `_incomplete` as mentioned in the search documentation)
- Workaround/alternative to multiple other requested enhancements including #464, #485, #569

## Try it first!

You can try this before it's merged by going here: https://deploy-preview-763--remote-jobs.netlify.app/ Please let me know if you see any issues.

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit b1f1975).  See below for details:

```

```

Please fix these issues and push a new commit to this pull request.

**Comment by nylen** [comment]
@dougaitken I guess I need to fix the bot before this is merged, otherwise it will probably keep causing problems later on. Please do try out the search though, it's ready to play with at https://deploy-preview-763--remote-jobs.netlify.app/

I also see "Loading search data... Infinity%" when this is hosted on Netlify. I'll fix that in this PR too.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit baafca9).  See below for details:

```
up to date in 0.294s
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 0c57976).  See below for details:

```
up to date in 0.315s
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 469f534).  See below for details:

```
up to date in 0.292s
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
:robot::warning: Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it. :warning::robot:

**Comment by auto-nylen** [comment]
:robot::warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot::warning:

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Comment by auto-nylen** [comment]
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 9e84e21). :heavy_check_mark:

**Comment by nylen** [comment]
OK, this is all good from my end.

**Comment by dougaitken** [comment]
Flipping 'eck. 

This is incredible. Are you using offline workers or something for the search? 

I can't break it so let's do this. 

I think for #464 and #569 we could maybe add things like `region:` type fitlers like how GitHub and other places use search terms? That said, this is such a huge improvement. Thank you so much.

**Comment by nylen** [comment]
Glad you like it, I had fun building it.

> Are you using offline workers or something for the search?

It's using https://lunrjs.com/ which if I remember correctly is the same library that [Calypso devdocs](https://wpcalypso.wordpress.com/devdocs) uses. The new code here uses Lunr to generate an index of all the data every time the site gets built. The index is just a different way to organize the data so that it can be searched quickly - basically a map of all the words that appear in our data and where they can be found. Then when you start searching on the site, it downloads the latest index data and the actual searching happens in your browser using that index.

> we could maybe add things like `region:` type filters

Good thing to look into for a future enhancement. This already works pretty well though - if you search for "react" then you're going to get all the companies that use React.

**Pull request merged**
