### PR TITLE
Added new Company 37signals

### PR DESCRIPTION
**Pull request by Ram-tyagi**
This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

### Added new company 

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**

* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
@Ram-tyagi your PR title isn't accurate 😉  Ideally one company per Pull Request. 

Rename both files as lowercase and check the reference in the readme is also lowercase, move 1Password above 37Signals.

**Review by dougaitken — CHANGES_REQUESTED** [review]
Rename both files as lowercase and check the reference in the readme is also lowercase, move 1Password above 37Signals.

**Comment by Ram-tyagi** [comment]
renamed in lowercase and placed in alphabetic order

**Comment by Ram-tyagi** [comment]
Done with all changes required @dougaitken

**Comment by dougaitken** [comment]
@Ram-tyagi The literal file name is still showing with uppercase S, can you rename the filename to `37signals.md`

**Comment by Ram-tyagi** [comment]
> @Ram-tyagi The literal file name is still showing with uppercase S, can you rename the filename to `37signals.md`

done with all the changes

**Review by dougaitken — APPROVED** [review]

**Comment by dougaitken** [comment]
Fantastic, thanks for the new addition @Ram-tyagi

**Pull request merged**
