### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amit429**
region cannot be world wide it has to specific
thats why i have done the correction for worldwide under region column
Or for world wide you will need another column

### CODE REVIEW

**Comment by dougaitken** [comment]
Hi @amit429 - do you mean this three companies are US only?

**Comment by amit429** [comment]
Yes sir

**Comment by dougaitken** [comment]
Hi @amit429 I know for a fact that 10Up are Global - https://10up.com/careers/

I'm closing this PR as it is invalid, please open a new one with related links if you want to update existing entries.

Thanks

**Comment by amit429** [comment]
Ok thank you

**Pull request closed without merging**
