### PR TITLE
Update mozilla.md

### PR DESCRIPTION
**Pull request by joshunger**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [ ] You know your alphabet - company is listed in alphabetical order in the README
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [ ] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details any restrictions to applicants based on geography
- [X] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by nylen** [comment]
Hi @joshunger, please have a look at the Markdown file you've modified [here](https://github.com/joshunger/remote-jobs/blob/669061360e5a600b6e3215f8168328a55341528e/company-profiles/mozilla.md) and note that right now, the placeholder text has effectively been moved from the "Company blurb" section to the "How to apply" section.

It would also be good to fill in as much info as possible about Mozilla while making changes here.  Ideally all of the sections in the [example company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) should be completed.

**Comment by joshunger** [comment]
That's all the information I have... what would you like to do?

**Comment by nylen** [comment]
I think that for Mozilla in particular, all of the information in our template is probably publicly available.

In any case we can't accept PRs that leave the company profiles badly formatted.

**Comment by joshunger** [comment]
👍

**Pull request closed without merging**
