### PR TITLE
Removed Featurist

### PR DESCRIPTION
**Pull request by LillyTS**
They ceased operations in 2023

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [x ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**

### CODE REVIEW

**Comment by dougaitken** [comment]
@LillyTS Can you delete the company profile as well, please?

**Comment by LilianaTS** [comment]
> @LillyTS Can you delete the company profile as well, please?

@dougaitken Okay I will!

**Comment by LillyTS** [comment]
> @LillyTS Can you delete the company profile as well, please?

Okay I will

**Review by dougaitken — APPROVED** [review]

**Comment by dougaitken** [comment]
Thanks @LillyTS - merged.

**Pull request merged**
