### PR TITLE
Add new company - ADEVA

### PR DESCRIPTION
**Pull request by Hanee-Solanki**
- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**
- [ ] You are an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- []x A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @Hanee-Solanki 

Unless you can change this to be more appropriate, this will be declined because of number 4 on the Pull Request template:

> The company directly hires employees. ** No bootcamps / freelance sites / etc**

You've also included a package-lock.json file change, why?

**Comment by Hanee-Solanki** [comment]
@dougaitken thank you so much for reviewing my code!

I will make the necessary changes to the pull request template.

Regarding the package.json file, to be honest, it was somehow changed by me. I later noticed that over 1000 lines were missing from it so changed it back to the original file.

**Comment by dougaitken** [comment]
@Hanee-Solanki To be clear - I'm not asking you to change the Pull Request template, I'm pointing out a line in that which needs to be confirmed correct. 

For the other file, if you can't remove those edits from the Pull Request then close this and start another with only the edits for the company

**Comment by Hanee-Solanki** [comment]
Hi @dougaitken, thank you for the clarification. 

I will go ahead, close this, and will create a new pull request. 

Thank you again!

**Pull request closed without merging**
