### PR TITLE
Add company profile for The Wirecutter

### PR DESCRIPTION
**Pull request by nylen**
This PR will serve as a test of our shiny new Travis config :sparkles: 

After the first commit, Travis should fail because we are linking to a non-existent file from the readme.

I'll add a company profile next, which should make the tests pass again.

### CODE REVIEW

**Comment by nylen** [comment]
```
$ node bin/validate.js
README.md: Broken link to company "The Wirecutter": "/company-profiles/the-wirecutter.md"
1 problem detected
The command "node bin/validate.js" exited with 1.
Done. Your build exited with 1.
```

:+1:

**Comment by nylen** [comment]
cc @rachelbaker - anything you would like to add for potential applicants to The Wirecutter?

**Comment by nylen** [comment]
```
$ node bin/validate.js
0 problems detected
The command "node bin/validate.js" exited with 0.
Done. Your build exited with 0.
```

:tada:

**Comment by dougaitken** [comment]
At some point the profile must have got deleted as I started The Wirecutter a while ago https://github.com/remoteintech/remote-jobs/pull/290/commits/a9be843637ec406d154776c1ae29ddf990be46fa

**Comment by dougaitken** [comment]
Pulling this in, if you feel there is anything to change / add, just lmk @rachelbaker 👍

**Pull request merged**
