### PR TITLE
PhishMe rebranded as Cofense

### PR DESCRIPTION
**Pull request by movermeyer**
See [press release](https://cofense.com/phishme-acquired-private-equity-syndicate-rebrands-cofense)

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [ ] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] Any missing parts from the profile, please use `<Unknown>` to allow for future completion
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @movermeyer, thanks for your contribution!

Our automated checks detected some problems with your pull request (as of commit 44c1d4d).  See below for details:

```
README.md: Expected 3 table cells but found 2: <td>Cofense</td><td><a href="https://cofense.com">https://cofense.com</a></td>

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
Hi @movermeyer, are you able to submit a company profile as well, please? Adding a timezone will also help on the readme

**Comment by auto-nylen** [comment]
Hi @movermeyer, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit eb3bd90). :white_check_mark:

**Comment by movermeyer** [comment]
I don't work there, but I did some digging on their site and made a profile.

**Comment by dougaitken** [comment]
Fantastic, thanks @movermeyer. I collated most of the original list, most of it was pure digging on company websites :) 

The top check in the list is just something for me to gauge interest

**Pull request merged**
