### PR TITLE
Add Joyent

### PR DESCRIPTION
**Pull request by bahamat**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @bahamat - can you clarify the "Region" aspect - are those countries/regions where you are hiring or where you have employees?

**Comment by bahamat** [comment]
It’s countries where we already have employees and it’s easy to hire.

**Comment by nylen** [comment]
@bahamat 

1. Does this mean that Joyent would hire employees from other countries or not?
2. Can you please update the PR accordingly? People use this field to determine whether they would be eligible for jobs listed on our site. If you are open to hiring from everywhere then the easiest thing to do would be to just change the region to "Worldwide".

**Comment by bahamat** [comment]
These are the ones where we can hire people easily, in part because we already have employees in those locales. Other locations are not impossible, but it’s much more difficult to make arrangements.

What would you recommend, or prefer to see I’m this case?

**Comment by nylen** [comment]
Just like what you said :) I think the best thing to do would be to leave the readme as-is, and write something like this in the company profile under the Region section:

>We can hire people easily in United States, Canada, United Kingdom, Singapore, and South Korea, in part because we already have employees in those locales. Other locations are not impossible, but it’s much more difficult to make arrangements.

**Comment by bahamat** [comment]
Ok, sounds good. I’ll push an update tomorrow.

**Comment by dougaitken** [comment]
Hey @bahamat 

Adding that comment to the company profile would be fantastic. If you are able to hire all over the world, but just have not yet, then "worldwide" on the main Readme is good. 

Working out what to show and hide is still a work in progress

**Comment by bahamat** [comment]
Sorry for the delay in updating this, but I've added the blurb for the region now.

**Pull request merged**
