### PR TITLE
Update reinteractive's website URL

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @lucascaton, thanks for the edit - are you able to create a company profile for this please?

**Comment by lucascaton** [comment]
@dougaitken sorry about the delay in getting back to you. I'll create one soon! Thanks.

**Comment by lucascaton** [comment]
Hey @dougaitken - I've asked someone to create a profile, could you please merge this PR and we create a new one once it's done? Thank you.

**Comment by dougaitken** [comment]
I'll close this out out @lucascaton, keep it all together - the company profile and the `net` > `com` change

**Pull request closed without merging**
