### PR TITLE
Create glenn-website-design

### PR DESCRIPTION
**Pull request by GlennMadden**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @GlennMadden, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 1ff1cb9).  See below for details:

```
glenn-website-design: Expected 1 first-level heading but found 0
glenn-website-design: The main title is wrapped inside of another element.
glenn-website-design: Company name looks wrong: ""
glenn-website-design: No link to company profile from readme
glenn-website-design: Required section "Company blurb" not found.
glenn-website-design: Content is not part of any section: <p>Glenn Website DesignCompany blurbAbout UsGlenn is a custom web design company that offers full-service web solutions for many types of business profiles including hotels, restaurants, e commerce shopping websites, interactive websites.Our Mission</p>
glenn-website-design: Content is not part of any section: <p>Company size5 currently (12/5/2019) and growing</p>
glenn-website-design: Content is not part of any section: <p>Remote statusAll of our company works remote. We communicate via email, messenger, and online chats</p>
glenn-website-design: Content is not part of any section: <p>RegionWorldwide</p>
glenn-website-design: Content is not part of any section: <p>Company technologiesWordPress, PHP, MySQL, Java</p>
glenn-website-design: Content is not part of any section: <p>Office locationsTulsa Oklahoma, Bandung IndonesiaHow to applyGlenn Website Design contact page</p>

11 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @dougaitken, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit a90e152).  See below for details:

```
glenn-website-design.md: No link to company profile from readme

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
this will work with #710

**Comment by nylen** [comment]
Hi @GlennMadden, just to recap what happened here:

Company profiles are Markdown files with headings and an expected structure, not plain text, so at first our review bot was complaining about that. @dougaitken has edited the file so that it's in the required format.

Now the readme file needs to be updated with a link to your company profile. As I noted on #710 this needs to be done in the same pull request (PR) as the other changes for your company.

The "correct" way to do this is to add a new commit to this branch using `git` and push the updated branch to GitHub. However since everyone is using the web interface there is another way. Start by grabbing the URL to edit a file that was modified in this PR, on the "Files changed" tab:

2019-12-14T05-32-09Z

In this case the URL is: https://github.com/GlennMadden/remote-jobs/edit/patch-4/company-profiles/glenn-website-design.md?pr=%2Fremoteintech%2Fremote-jobs%2Fpull%2F709

The format of this URL is
`https://github.com/USER-NAME/REPO-NAME/edit/BRANCH-NAME/FILE-PATH.EXT?pr=LINK-TO-PR`
Now we'll modify it to edit the main readme file instead &rarr; https://github.com/GlennMadden/remote-jobs/edit/patch-4/README.md?pr=%2Fremoteintech%2Fremote-jobs%2Fpull%2F709

There are other ways to get to this screen but I think this is the easiest. Either of you should be able to visit that link. There you can add the readme line from #710, type in an appropriate commit message at the bottom, and click "Commit" using the "Commit directly to the `patch-4` branch" option. After that, the new commit will appear on this PR, and this PR should be all set.

Please leave this PR open and we'll get it finished here. It's always better to work in a single PR when possible, opening multiple PRs causes duplicate work and makes any conversation about the changes harder to follow since the conversation gets split across multiple places.

**Pull request merged**
