### PR TITLE
Added Aula.md

### PR DESCRIPTION
**Pull request by WillemWijnans**
The pull request adheres to the repository's Code of Conduct ✅
If the company is at least partially remote ✅
If you add the company in alphabetical order in the list ✅
If you submit the company with a website ✅
If you submit the company with the regions that are accepted for remote positions (for more details see the instructions in the example company profile) ✅
If you submit a company profile page and link the company name to it (see example here) ✅

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Sounds interesting! Thanks for the addition @WillemWijnans

**Comment by WillemWijnans** [comment]
Hey Doug,

thanks!

I see it did not end up in the companies dir but in the main dir.

**Comment by nylen** [comment]
yep this PR wasn't done quite right.  #561 is a follow-up but it's not quite there either.

**Comment by dougaitken** [comment]
Bah, didn't check it properly, thanks @nylen @WillemWijnans 

if you can fix up the new PR, that'll come in

**Pull request merged**
