### PR TITLE
Improve SmugMug’s company blurb

### PR DESCRIPTION
**Pull request by onethumb**
Adds extra context to SmugMug’s listing, adhereing to the Contributing Guidelines and Code of Conduct.

I am the co-founder, CEO & Chief Geek at SmugMug. We love remote workers.

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @onethumb, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 6c4fba6).  See below for details:

```
smugmug.md: Profile looks complete, but the main readme contains a warning emoji.

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by dougaitken** [comment]
👋 Hey Don!

I replied on Twitter but looping back here. 
What you'll want to do is open up the `README.md` file on your own fork, scroll to the line with SmugMug, then remove the ⚠️ icon.
Then save that file and commit that, then push that commit to the master branch. 
That will in turn update this Pull Request. 

Let me know how you get on!

**Comment by auto-nylen** [comment]
Hi @onethumb, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit 632ec33). :heavy_check_mark:

**Comment by onethumb** [comment]
@dougaitken Thanks for the Tweet! All fixed up. :)

**Comment by dougaitken** [comment]
Toot toot, here we go! 

Thanks @onethumb

**Pull request merged**
