### PR TITLE
AgileBits -> 1Password

### PR DESCRIPTION
**Pull request by Penderworth**
We're rebranding our company to focus on 1Password, so I wanted to update this as well.

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details any restrictions to applicants based on geography
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @Penderworth if you're able to edit the readme from `AgileBits` to `1Password` that would be great - https://github.com/remoteintech/remote-jobs/blob/master/README.md

**Comment by Penderworth** [comment]
@dougaitken I actually can't figure out how to do that in this PR... 😄

**Comment by auto-nylen** [comment]
Hi @nylen, thanks for updating the pull request!  According to our automated checks, everything looks OK now (as of commit f088e19). :heavy_check_mark:

**Comment by nylen** [comment]
Thanks for the PR @Penderworth - I updated the readme.

**Pull request merged**
