### PR TITLE
Feature/added target blank external icon for links

### PR DESCRIPTION
**Pull request by christyram99**
This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] This PR contains housekeeping only (URL edits, copy changes etc)

### CODE REVIEW

**Comment by dougaitken** [comment]
@christyram99 Thanks for having a great at this.

* Is this future proof?
* Will show anything that isn't a n `remoteintech.company` as an external URL?
* These are opening in a new tab, yes? Rather than showing it is an external site?

**Comment by christyram99** [comment]
1.Yeah it is future proof.
2.I didn't added any condition for checking that is our company. I will add
those changes.
3. All external links are opening new tab. Are you saying we don't need an
external over link icon there?

**Comment by christyram99** [comment]
#1024 need to merge before this pull request.

**Comment by dougaitken** [comment]
Can you walk me through the files included there, please @christyram99? 

Does this generate the external link icon and add the target blank on page build? Ideally this doesn't change the GutHub repository but handles it on Netlify when the site is built.

**Comment by christyram99** [comment]
Hi @dougaitken , I can explain what files are changing in the pull request. 

Firstly, this will generate external links and icons only in netlify build only. I changed the files for link and icons generation and also updated the test files to check those are generating correctly.

File changes:
1. **lib/index.js** External links checking and extern icon adding
2. **test/fixtures/valid-incomplete/parsed-content/*** Update test files to test the external links and icons are correctly generating
3. **site/templates/base.html** Added external link for footer links
4. **site/templates/company.html** Added external links and icons for main link

**Comment by Maclain272** [comment]
thanks your  guys for helps and stay in touch for anything it coming up next.

**Review by dougaitken — APPROVED** [review]

**Comment by dougaitken** [comment]
Thanks @christyram99 

If this breaks, I blame you 😂 I don't have my technical maintainer to help out here so worst thing is I revert this.

**Comment by christyram99** [comment]
Sure @dougaitken . I am hoping this will not fail.

**Pull request merged**
