### PR TITLE
Create CONTRIBUTING.md (Issue #482)

### PR DESCRIPTION
**Pull request by owengaspard**
I have added a small contributing guide for anyone looking to contribute to this project. This refers to issue #482.

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**

### CODE REVIEW

**Comment by KieranRobson** [comment]
https://github.com/remoteintech/remote-jobs/blob/main/.github/CONTRIBUTING.md already exsists

**Comment by KieranRobson** [comment]
A standard contributing document already exists, #482 referes to a technical contributing document to help with the site (https://remoteintech.company/).

**Comment by dougaitken** [comment]
Yes @owengaspard, I appreciate your enthusiasm but @KieranRobson is correct, as mentioned in the Issue content and my comment, it is based around how the site is built rather than contributing to the list. 

Also, `companies` remains lowercase and that section about ⚠️ will remain on the main page until I fully clean up the list.

**Comment by dougaitken** [comment]
Hi @owengaspard 

If you're still wanting to make a technical contributing document, please do open a new Pull Request with the details. Thanks.

**Pull request closed without merging**
