### PR TITLE
Added Ergeon to the list

### PR DESCRIPTION
**Pull request by leapnthamix**
Ergeon is the company I work for and we are an all-remote company.

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/master/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/master/CODE_OF_CONDUCT.md).

- [x] I am an employee of the company mentioned and confirm all included details are correct
- [ ] This PR contains housekeeping only (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

### CODE REVIEW

**Comment by auto-nylen** [comment]
Hi @leapnthamix, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit a6abbc7).  See below for details:

```
README.md: Invalid link to company profile for "Ergeon": "/company-profiles/ergeon"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by auto-nylen** [comment]
Hi @leapnthamix, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 4872c50).  See below for details:

```
README.md: Missing company profile for "Ergeon", or broken link: "/company-profiles/ergeon.md"

1 problem detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by leapnthamix** [comment]
Hi,
I checked the company profile is linked correctly. Can you tell me what's wrong with it. Thanks!

**Comment by auto-nylen** [comment]
Hi @leapnthamix, thanks for your contribution!

Our automated checks detected some problems with this pull request (as of commit 99ea4bf).  See below for details:

```
ergeon.md: Invalid section: "<strong>Company Blurb</strong>".  Expected one of: ["Company blurb","Company size","Remote status","Region","Company technologies","Office locations","How to apply"]
ergeon.md: Required section "Company blurb" not found.

2 problems detected
```

Please fix these issues and push a new commit to this pull request.

**Comment by edelstone** [comment]
@leapnthamix The issue is likely the bold-facing stars you have wrapped around the headers in the markdown. If you re-open this, remove those, and try again I think it will stop alerting you to errors.

**Pull request closed without merging**
